export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const GET_BURGER_CONSTRUCTOR_INGREDIENTS = 'GET_BURGER_CONSTRUCTOR_INGREDIENTS';
export const GET_INFO_OPEN_INGREDIENT_MODAL = 'GET_INFO_OPEN_INGREDIENT_MODAL'
export const CLEAR_INGREDIENT_OPEN = 'CLEAR_INGREDIENT_OPEN'
export const GET_ID_INGREDIENTS_FOR_ORDER = 'GET_ID_INGREDIENTS_FOR_ORDER'
export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const GET_ORDER_NUMBER = 'GET_ORDER_NUMBER'
export const CHANGE_INGREDIENT = 'CHANGE_INGREDIENT'
export const ADD_BUN = 'ADD_BUN'

export const REGISTER_USER = 'REGISTER_USER'

export const LOGIN_USER = 'LOGIN_USER'
export const GET_PROFILE_INFO = 'GET_PROFILE_INFO'
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const RESET_PASSWORD = 'RESET_PASSWORD'


