export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const GET_BURGER_CONSTRUCTOR_INGREDIENTS = 'GET_BURGER_CONSTRUCTOR_INGREDIENTS';
export const GET_INFO_OPEN_INGREDIENT_MODAL = 'GET_INFO_OPEN_INGREDIENT_MODAL'
export const CLEAR_INGREDIENT_OPEN = 'CLEAR_INGREDIENT_OPEN'
export const GET_ID_INGREDIENTS_FOR_ORDER = 'GET_ID_INGREDIENTS_FOR_ORDER'
